### ISSUE TITLE
Option to disable Invite suppression [Feature Request]

### ISSUE THREAD

**Issue by mailbun** [Pexilo/Stealthy#5]
Just a simple request:
It would be useful to disable deleting of invite links in some rare usecases, and I have not found this in help nor setup menus

**Comment by Pexilo** [comment]
Hey @jilinoleg, thank you for your request 😄
This was actually in the roadmap, but I fixed it asap since you asked!
The feature is live, you can check the release for more details [1.1.4](https://github.com/Pexilo/Stealthy/releases/tag/1.1.4)

Thanks for using Stealthy, feel free to report issues if you encounter any.
